{% set name = "sanitize_ml_labels" %}
{% set version = "1.0.51" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sanitize_ml_labels-{{ version }}.tar.gz
  sha256: 421924013ee58d16d03e9d42d190b685095e89f7ce738f9d597a953ff3bce0eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - compress_json

test:
  imports:
    - sanitize_ml_labels
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/LucaCappelletti94/sanitize_ml_labels
  summary: Simple python package to sanitize in a standard way ML-related labels.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dillonroach
    - isuruf
