{% set name = "sanitize_ml_labels" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sanitize_ml_labels-{{ version }}.tar.gz
  sha256: f28be5075f8b12ba6043beac40d3df8c653db8477e22df93a4a41df784b51138

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - compress_json

test:
  imports:
    - sanitize_ml_labels
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LucaCappelletti94/sanitize_ml_labels
  summary: Simple python package to sanitize in a standard way ML-related labels.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dillonroach
    - isuruf
